// src/views/Projects.vue
<template>
  <div id="projects">
    <Navbar/>

    <h2>Projects:</h2>

    <div class='card'>
      <h3>🫖 kettle</h3>
      <p>
        A boilerplate manager cli-tool built with Rust
      </p>
      <a href="https://github.com/saravenpi/kettle" target="_blank">github</a>
    </div>

    <div class='card'>
      <h3>🍂 drop-game</h3>
      <p>
        An overlay game that reacts to a twitch chat
      </p>
      <a href="https://github.com/saravenpi/drop-game" target="_blank">github</a>
    </div>

    <div class='card'>
      <h3>📷 ascii_camera</h3>
      <p>
        A cli app that creates a live ascii art from your camera !
      </p>
      <a href="https://github.com/saravenpi/ascii_camera" target="_blank">github</a>
    </div>

    <div class='card'>
      <h3>⌨️ speed_typing_test</h3>
      <p>
        A cli speed typing test with random english words !
      </p>
      <a href="https://github.com/saravenpi/speed_typing_test" target="_blank">github</a>
    </div>
    
    <div class='card'>
      <h3>📦 uuids</h3>
      <p>
        This is an easy to use npm package to generate unique ID's for your projects !
      </p>
      <a href="https://github.com/saravenpi/uuids" target="_blank">github</a>
    </div>
  </div>
</template>

<script>
import Navbar from '../components/Navbar.vue'

export default {
  name: 'projects',
  components: {
    Navbar
  },
}
</script>

<style scoped>
.card h3 {
  text-decoration: bold;
}
</style>

// src/routes/projects/+page.svelte
<script>
</script>
<div>
    <div class="m-28 rounded p-10">
        <div class="grid grid-cols-4 mb-10 gap-4">
            <a href="/">
                <div class="text-xl bg-stone-200 rounded p-3 hover:bg-stone-400">
                    Home
                </div>
            </a>
            <a href="/projects">
                <div class="text-xl bg-stone-500 rounded p-3 hover:bg-stone-400 text-white">
                    Projects
                </div>
            </a>
            <a href="/skills">
                <div class="text-xl bg-stone-200 rounded p-3 hover:bg-stone-400">
                    Skills
                </div>
            </a>
        </div>

        <div class="text-4xl mb-5">
            Projects:
        </div>
        <div class="grid grid-cols-3 gap-4">
            <a href="https://kettle-app.vercel.app">
                <div class="bg-stone-300 p-10 rounded hover:bg-stone-400">
                    <div class="text-3xl mb-3">
                        🫖 kettle
                    </div>
                    <div class="text-xl">
                        Kettle is a boilerplate manager, locally or in the cloud.
                        <br>
                        It helps you to start projects faster.
                    </div>
                </div>
            </a>
            <a href="https://github.com/saravenpi/drop-game">
                <div class="bg-stone-300 p-10 rounded hover:bg-stone-400">
                    <div class="text-3xl mb-3">
                        🍂 drop-game
                    </div>
                    <div class="text-xl">
                        A twitch overlay game that reacts to the chat
                    </div>
                </div>
            </a>
            <a href="https://github.com/saravenpi/ascii_camera">
                <div class="bg-stone-300 p-10 rounded hover:bg-stone-400">
                    <div class="text-3xl mb-3">
                        📷 ascii_camera
                    </div>
                    <div class="text-xl">
                        Program that creates a live ascii art from your camera
                    </div>
                </div>
            </a>
            <a href="https://github.com/saravenpi/speed_typing_test">
                <div class="bg-stone-300 p-10 rounded hover:bg-stone-400">
                    <div class="text-3xl mb-3">
                        📷 speed_typing_test
                    </div>
                    <div class="text-xl">
                        Program that tests your typing speed with random words
                    </div>
                </div>
            </a>
            <a href="https://github.com/saravenpi/speed_typing_test">
                <div class="bg-stone-300 p-10 rounded hover:bg-stone-400">
                    <div class="text-3xl mb-3">
                        📦 uuids
                    </div>
                    <div class="text-xl">
                        An npm package to generate unique ids for your projects
                    </div>
                </div>
            </a>

        </div>
    </div>
</div>
<style lang="postcss">
    :global(html) {
        background-color: #white;
    }
</style>
