// src/lib/components/sections/Home.svelte
<script>
  import { onMount } from "svelte";

  let music_text = null;
  const url = "https://ws.audioscrobbler.com/2.0/?method=user.getrecenttracks&user=saravenpi&api_key=d2cafb7e30ed8b064a00fb67693d2a70&format=json";

  onMount(() => {
    fetch(url).then((response) => {
      response.json().then((data) => {
        const lasttrack = data.recenttracks.track[0];
        if (lasttrack["name"]) {
          const artist = lasttrack.artist["#text"];
          const title = lasttrack.name;
          music_text = `${title} by ${artist}`;
        }
      });
    });
  });
</script>

<main>
  <img
    alt="avatar"
    src="https://avatars.githubusercontent.com/u/61117321"
    class="avatar"
  />

  <h1>Hi I'm Saravenpi</h1>

  <p>I'm a 23 fullstack software developer</p>
  <p>Interested into decentralisation</p>

  <p>
    <a href="https://github.com/saravenpi" target="_blank" rel="noopener noreferrer">GitHub</a> |
    <a href="https://x.com/saravenpi" target="_blank" rel="noopener noreferrer">Twitter</a> |
    <a href="mailto:saravenpi@tuta.io">Email</a>
  </p>

  {#if music_text}
    <p>🎧 Listening Now: {music_text}</p>
  {/if}
</main>

// src/Home.vue
<template>
  <div id="home">
      <div class="container">
        <Navbar/>

          <div class="content">
            <div id="music-status">

            </div>
              <h1>
                <div class="profile">
                  <img src="https://avatars.githubusercontent.com/u/61117321" class="avatar"> <div class="username"> Saravenpi</div>
                </div>
              </h1>

              <p>
                  Hello, my name is Sara and I'm a fullstack web developer! I'm constantly learning new languages and frameworks!

                  <h1>Contact:</h1>
                    Get in touch with me on Twitter/Telegram/Github <a href="https://twitter.com/saravenpi" target="_blank"><code>@saravenpi</code></a>

                  <h1>Donate:</h1>
                  <a href="https://buymeacoffee.com/saravenpi" target="_blank"><div class="donate">Buy me a coffee</div></a>
              </p>
          </div>

      </div>

    </div>


</template>
<script src="https://unpkg.com/vue-router/dist/vue-router.js"></script>

<script>
import Navbar from './components/Navbar.vue'

export default {
  name: 'app',
  components: {
    Navbar
  },
  created: function () {

    fetch("https://ws.audioscrobbler.com/2.0/?method=user.getrecenttracks&user=saravenpi&api_key=d2cafb7e30ed8b064a00fb67693d2a70&format=json")
    .then(function(response){
      response.json().then(data => {
        var lasttrack = data.recenttracks.track[0]
        if (lasttrack["@attr"]) {
          var artist = lasttrack.artist['#text']
          var title = lasttrack.name
          var info = `<i class="material-icons">headphones</i><span>&nbsp;Listening Now:&ensp;</span>`
          var listening = `<a href="${lasttrack.url}" target=”_blank”>${title} by ${artist}`
          document.getElementById("music-status").innerHTML =  info + listening

        } else {
            document.getElementById("music-status").innerHTML = null
        }

      })
    })
  }
}
</script>



<style src="./assets/style.css">

</style>
